"use client";
import {Bookmark,ChevronDown,Info,Minus,Plus,Share2} from "lucide-react";
import {useState} from "react";

export default function MatchPage(){
 const [mode,setMode]=useState("Buy"),[outcome,setOutcome]=useState("YES"),[amount,setAmount]=useState(0),[slippage,setSlippage]=useState(10),[fill,setFill]=useState(false);
 return <div className="mx-auto max-w-[1500px] bg-transparent pb-24 text-[#f4f4f5]"><div className="grid gap-8 xl:grid-cols-[minmax(0,2.2fr)_minmax(360px,.95fr)]">
  <div className="min-w-0">
   <header><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3 text-lg font-bold"><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-lg">🏆</span>FIFA World Cup 2026™</div><div className="flex items-center gap-6 text-sm text-[#a1a1aa]"><span>Starts · 7h · 11m</span><Share2 size={18}/><Bookmark size={18}/></div></div><h1 className="mt-5 font-heading text-3xl font-bold">Norway vs England</h1></header>
   <section className="mt-10 grid grid-cols-[1fr_auto_1fr] items-center rounded-2xl bg-[#19191d] px-6 py-10 text-center sm:px-14"><Team flag="🇳🇴" name="Norway"/><div><div className="text-xl font-bold">02:45</div><div className="mt-3 text-sm text-[#a1a1aa]">July, 12</div></div><Team flag="🏴" name="England"/></section>
   <section className="mt-10 rounded-2xl bg-[#19191d] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="text-[#a1a1aa]">Volume: <strong className="text-lg text-white">$4,050,850</strong></div><div className="flex rounded-xl bg-[#111114] p-1">{["Live","1h","1d","1w","1m"].map((x,i)=><button key={x} className={"rounded-lg px-4 py-2 text-sm font-semibold "+(i===0?"bg-[#2c2c33]":"text-[#a1a1aa]")}>{x}</button>)}</div></div><MatchChart/></section>
   <section className="mt-10 overflow-hidden rounded-2xl bg-[#19191d]"><div className="flex items-start justify-between border-b border-white/[0.06] p-6"><div><div className="flex items-center gap-2 text-lg font-bold">Moneyline <span className="text-sm font-normal text-[#a1a1aa]">Regular Time</span><Info size={16}/></div><div className="mt-2 text-sm text-[#a1a1aa]">$2.3M Vol.</div></div><div className="text-right"><div className="text-[#20d38a]">Open</div><div className="mt-2 text-lg font-bold">25%</div></div></div><div className="grid gap-3 p-5 sm:grid-cols-3"><Outcome name="NOR" value="25% · 25¢" tone="cyan"/><Outcome name="DRAW" value="26% · 27¢" tone="neutral"/><Outcome name="ENG" value="50% · 51¢" tone="red"/></div></section>
  </div>
  <aside className="space-y-7 xl:sticky xl:top-24 xl:self-start">
   <section className="overflow-hidden rounded-2xl bg-[#19191d] shadow-2xl">
    <div className="p-5"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl border border-white/[0.08] bg-[#111114] text-3xl">🇳🇴</span><div><div className="text-sm text-[#a1a1aa]">Norway vs England</div><div className="mt-1 text-lg font-bold">NOR</div></div></div><div className="mt-6 flex items-center justify-between"><div className="flex rounded-xl bg-[#111114] p-1">{["Buy","Sell"].map(x=><button key={x} onClick={()=>setMode(x)} className={"rounded-lg px-5 py-2 font-semibold "+(mode===x?"bg-[#3b3b43]":"text-[#a1a1aa]")}>{x}</button>)}</div><button className="flex items-center gap-8 rounded-xl bg-[#232328] px-5 py-3 font-semibold">Market <ChevronDown size={16}/></button></div></div>
    <div className="grid grid-cols-2 gap-3 border-y border-white/[0.06] p-5"><TradeChoice label="YES" price="25¢" selected={outcome==="YES"} onClick={()=>setOutcome("YES")} yes/><TradeChoice label="NO" price="76¢" selected={outcome==="NO"} onClick={()=>setOutcome("NO")}/></div>
    <div className="border-b border-white/[0.06] p-5"><div className="flex justify-between text-[#a1a1aa]"><span>Amount</span><span>Cash: <b className="text-white">—</b></span></div><div className="mt-2 text-4xl font-bold text-[#6f6f78]"><span>$</span>{amount.toFixed(2)}</div><div className="mt-5 flex flex-wrap items-center gap-2">{[5,25,50,100].map(x=><button key={x} onClick={()=>setAmount(v=>v+x)} className="rounded-full bg-[#3b3b43] px-3 py-1 text-sm font-semibold">+<span>$</span>{x}</button>)}<button onClick={()=>setAmount(100)} className="ml-auto text-sm font-bold text-[#a1a1aa] underline">MAX</button></div></div>
    <div className="border-b border-white/[0.06] p-5"><div className="text-[#a1a1aa]">Max slippage</div><div className="mt-4 grid grid-cols-[1fr_2fr_1fr] items-center rounded-xl bg-[#232328] p-2"><button onClick={()=>setSlippage(Math.max(1,slippage-1))} className="grid h-12 place-items-center"><Minus/></button><div className="text-center text-2xl font-bold">{slippage}%</div><button onClick={()=>setSlippage(Math.min(25,slippage+1))} className="grid h-12 place-items-center"><Plus/></button></div><div className="mt-6 flex items-center justify-between text-[#a1a1aa]"><span>Fill policy</span><button onClick={()=>setFill(!fill)} className={"relative h-9 w-16 rounded-full "+(fill?"bg-[#20d38a]":"bg-[#3b3b43]")}><span className={"absolute top-1 h-7 w-7 rounded-full bg-white transition "+(fill?"left-8":"left-1")}/></button></div></div>
    <div className="p-5"><button className="h-15 w-full rounded-full bg-[#f4f4f5] text-lg font-bold text-[#0a0a0c]">Sign in to predict</button></div>
   </section>
   <section className="rounded-2xl bg-[#19191d] p-5"><h2 className="text-[#c9c9ce]">Recent Trades</h2><div className="mt-5 flex items-center justify-between border-b border-white/[0.06] pb-5"><div><div className="flex items-center gap-2 font-bold"><span className="text-2xl">🇳🇴</span>NOR <span className="rounded bg-[#0e2a20] px-2 py-1 text-xs text-[#20d38a]">Yes</span><span className="rounded bg-[#3a1a22] px-2 py-1 text-xs text-[#fa4669]">Sell</span></div><div className="mt-1 text-xs text-[#6f6f78]">1s ago</div></div><div className="text-right"><b>$7.03</b><div className="mt-1 text-sm text-[#a1a1aa]">30.56 shares</div></div></div></section>
  </aside>
 </div></div>
}
function Team({flag,name}:{flag:string;name:string}){return <div><div className="text-5xl">{flag}</div><div className="mt-3 text-lg font-bold">{name}</div></div>}
function Outcome({name,value,tone}:{name:string;value:string;tone:string}){const c=tone==="cyan"?"bg-[#0e2a20] text-[#20d38a]":tone==="red"?"bg-[#3a1a22] text-[#fa4669]":"bg-[#2c2c33]";return <button className={"flex h-15 items-center justify-between rounded-full px-6 text-lg font-bold "+c}><span>{name}</span><span>{value}</span></button>}
function TradeChoice({label,price,selected,yes,onClick}:{label:string;price:string;selected:boolean;yes?:boolean;onClick:()=>void}){return <button onClick={onClick} className={"flex h-15 items-center justify-between rounded-full px-6 text-lg font-bold "+(yes?(selected?"bg-[#20d38a] text-[#0a0a0c]":"bg-[#0e2a20] text-[#20d38a]"):(selected?"bg-[#fa4669]":"bg-[#3a1a22] text-[#fa4669]"))}><span>{label}</span><span>{price}</span></button>}
function MatchChart(){return <svg viewBox="0 0 850 300" className="mt-5 h-[300px] w-full" aria-label="Market probability history">{[40,105,170,235,275].map(y=><line key={y} x1="0" x2="815" y1={y} y2={y} stroke="#29292f" strokeDasharray="3 7"/>)}<polyline points="0,72 650,72" fill="none" stroke="#fa4669" strokeWidth="2"/><polyline points="0,235 110,235 115,226 120,235 650,235" fill="none" stroke="#a1a1aa" strokeWidth="2"/><polyline points="0,244 650,244" fill="none" stroke="#20d38a" strokeWidth="2"/><circle cx="650" cy="72" r="22" fill="#3a1a22"/><circle cx="650" cy="72" r="5" fill="#fa4669"/><circle cx="650" cy="235" r="22" fill="#2c2c33"/><circle cx="650" cy="235" r="5" fill="#a1a1aa"/><circle cx="650" cy="244" r="22" fill="#0e2a20"/><circle cx="650" cy="244" r="5" fill="#20d38a"/><text x="668" y="68" fill="#fa4669" fontSize="15">ENG</text><text x="668" y="88" fill="#fa4669" fontSize="21" fontWeight="700">50%</text><text x="668" y="220" fill="#a1a1aa" fontSize="15">DRAW</text><text x="668" y="240" fill="#a1a1aa" fontSize="21">26%</text><text x="668" y="260" fill="#20d38a" fontSize="15">NOR 25%</text>{[[110,"19:32"],[430,"19:33"],[750,"19:34"]].map(i=><text key={i[1]} x={Number(i[0])} y="295" textAnchor="middle" fill="#6f6f78" fontSize="13">{i[1]}</text>)}</svg>}