import Link from "next/link";
import { Crown, Flame, Medal, ShieldCheck, Target, TrendingUp, Trophy } from "lucide-react";
import DemoNotice from "@/components/kicktick/DemoNotice";

const TRADERS = [
  ["1", "PitchOracle", "Argentina", "78%", "12", "8.4 SOL", "YES"], ["2", "CornerKing", "France", "74%", "9", "6.9 SOL", "NO"], ["3", "NinetyPlus", "Japan", "71%", "8", "5.7 SOL", "YES"], ["4", "CleanSheet", "Brazil", "69%", "7", "4.8 SOL", "NO"], ["5", "xGMerchant", "Germany", "67%", "6", "4.2 SOL", "YES"],
];

export default function LeaderboardPage() {
  const cards = [[Target, "Most Accurate", "PitchOracle", "78% hit rate"], [Flame, "Best Streak", "CornerKing", "9 correct"], [TrendingUp, "Biggest Payout", "NinetyPlus", "3.8 SOL"], [Crown, "Top YES Trader", "xGMerchant", "64 YES buys"], [ShieldCheck, "Top NO Trader", "CleanSheet", "59 NO buys"]];
  return <div className="space-y-6 pb-10 text-slate-100"><header className="rounded-[28px] border border-white/[0.08] bg-[#07112b] p-6 sm:p-8"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-violet-300"><Trophy size={16} />Fan performance</div><h1 className="mt-3 font-heading text-4xl font-bold text-white">Top Predictors</h1><p className="mt-3 text-sm text-slate-400">Accuracy, winning streaks, payouts, YES/NO conviction, and national team supporter rankings.</p></header><DemoNotice /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([Icon, title, name, value]) => { const C = Icon as typeof Trophy; return <div key={String(title)} className="rounded-2xl border border-white/[0.08] bg-[#0d142b] p-4"><C size={18} className="text-cyan-300" /><div className="mt-4 text-[10px] font-bold uppercase text-slate-500">{String(title)}</div><div className="mt-1 font-heading text-lg font-bold text-white">{String(name)}</div><div className="mt-1 text-xs text-cyan-300">{String(value)}</div></div>; })}</section><section className="overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0d142b]"><div className="flex items-center justify-between border-b border-white/[0.08] p-5"><h2 className="font-heading text-xl font-bold text-white">World Cup leaderboard</h2><span className="text-xs text-amber-300">Demo leaderboard</span></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{["Rank", "Predictor", "Team", "Accuracy", "Best streak", "Total claimed", "Bias"].map((label) => <th key={label} className="px-5 py-3 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-white/[0.06]">{TRADERS.map(([rank, name, team, accuracy, streak, payout, bias]) => <tr key={name} className="hover:bg-white/[0.025]"><td className="px-5 py-4"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-white/[0.06] font-bold text-white">{rank === "1" ? <Medal size={15} className="text-amber-300" /> : rank}</span></td><td className="px-5 py-4 font-semibold text-white">{name}</td><td className="px-5 py-4 text-slate-400">{team}</td><td className="px-5 py-4 font-bold text-emerald-300">{accuracy}</td><td className="px-5 py-4 text-slate-300">{streak}</td><td className="px-5 py-4 text-violet-300">{payout}</td><td className={"px-5 py-4 font-bold " + (bias === "YES" ? "text-emerald-300" : "text-rose-300")}>{bias}</td></tr>)}</tbody></table></div></section><div className="flex justify-center"><Link href="/events" className="rounded-full bg-cyan-300 px-6 py-3 text-sm font-bold text-[#010820]">Explore markets</Link></div><p className="text-xs text-amber-200">Demo leaderboard — simulated activity data.</p></div>;
}
