export type KickTickMarketFamily =
  | "Live"
  | "Goals"
  | "Corners"
  | "Penalties"
  | "Offsides"
  | "Cards"
  | "Totals"
  | "Goal Gap"
  | "Match Result"
  | "Resolved";

export type KickTickMarketStatus = "LIVE" | "TODAY" | "UPCOMING" | "RESOLVED";

export type KickTickMarket = {
  id: string;
  fixtureId: string;
  matchName: string;
  homeTeam: string;
  awayTeam: string;
  status: KickTickMarketStatus;
  clock: string;
  score: string;
  family: KickTickMarketFamily;
  question: string;
  yesProbability: number;
  noProbability: number;
  poolSol: string;
  volumeSol: string;
  timeLeft: string;
  window?: string;
  dataSource: "TxLINE-compatible score data" | "Simulated TxLINE-compatible event data";
  proofStatus: "verified-devnet" | "demo" | "pending";
  demoOnly?: boolean;
  tradeHref: string;
  description: string;
};

export const KICKTICK_FAMILIES: KickTickMarketFamily[] = [
  "Live",
  "Goals",
  "Corners",
  "Penalties",
  "Offsides",
  "Cards",
  "Totals",
  "Goal Gap",
  "Match Result",
  "Resolved",
];

export const WORLD_CUP_FILTERS = [
  "All",
  "Live",
  "Today",
  "Upcoming",
  "Resolved",
  "5m",
  "15m",
  "45m",
  "Goals",
  "Corners",
  "Penalties",
  "Offsides",
  "Cards",
  "Totals",
  "Goal Gap",
  "Match Result",
] as const;

export const KICKTICK_MARKETS: KickTickMarket[] = [
  // ── Goal Window Markets (working devnet flow) ─────────────────────────
  {
    id: "arg-bra-goal-5m",
    fixtureId: "WC26-DEMO-ARG-BRA",
    matchName: "Argentina vs Brazil",
    homeTeam: "Argentina",
    awayTeam: "Brazil",
    status: "LIVE",
    clock: "63:20",
    score: "ARG 1 - 1 BRA",
    family: "Live",
    question: "Goal in Next 5m?",
    yesProbability: 58,
    noProbability: 42,
    poolSol: "6.4 SOL",
    volumeSol: "18.7 SOL",
    timeLeft: "00:32",
    window: "63:00 -> 68:00",
    dataSource: "TxLINE-compatible score data",
    proofStatus: "verified-devnet",
    tradeHref: "/live",
    description: "Working live goal-window flow using marketKind 1 and YES/NO on-chain positions.",
  },
  {
    id: "arg-bra-goal-15m",
    fixtureId: "WC26-DEMO-ARG-BRA",
    matchName: "Argentina vs Brazil",
    homeTeam: "Argentina",
    awayTeam: "Brazil",
    status: "LIVE",
    clock: "63:20",
    score: "ARG 1 - 1 BRA",
    family: "Goals",
    question: "Goal in Next 15m?",
    yesProbability: 71,
    noProbability: 29,
    poolSol: "9.8 SOL",
    volumeSol: "24.1 SOL",
    timeLeft: "01:00",
    window: "63:00 -> 78:00",
    dataSource: "TxLINE-compatible score data",
    proofStatus: "verified-devnet",
    tradeHref: "/live",
    description: "Longer live goal window resolved from start and end score totals.",
  },
  {
    id: "arg-bra-goal-45m",
    fixtureId: "WC26-DEMO-ARG-BRA",
    matchName: "Argentina vs Brazil",
    homeTeam: "Argentina",
    awayTeam: "Brazil",
    status: "LIVE",
    clock: "63:20",
    score: "ARG 1 - 1 BRA",
    family: "Goals",
    question: "Goal before full-time?",
    yesProbability: 82,
    noProbability: 18,
    poolSol: "12.2 SOL",
    volumeSol: "31.6 SOL",
    timeLeft: "02:41",
    window: "63:00 -> 90:00",
    dataSource: "TxLINE-compatible score data",
    proofStatus: "verified-devnet",
    tradeHref: "/live",
    description: "Demo maps the 45m window onto the existing live-goal market implementation.",
  },
  {
    id: "arg-bra-home-goal-5m",
    fixtureId: "WC26-DEMO-ARG-BRA",
    matchName: "Argentina vs Brazil",
    homeTeam: "Argentina",
    awayTeam: "Brazil",
    status: "LIVE",
    clock: "63:20",
    score: "ARG 1 - 1 BRA",
    family: "Goals",
    question: "Argentina goal in next 5m?",
    yesProbability: 34,
    noProbability: 66,
    poolSol: "3.2 SOL",
    volumeSol: "7.8 SOL",
    timeLeft: "00:32",
    window: "63:00 -> 68:00",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Team-specific goal market. Demo until team-level score parsing is wired.",
  },
  {
    id: "arg-bra-no-goal-ht",
    fixtureId: "WC26-DEMO-ARG-BRA",
    matchName: "Argentina vs Brazil",
    homeTeam: "Argentina",
    awayTeam: "Brazil",
    status: "LIVE",
    clock: "63:20",
    score: "ARG 1 - 1 BRA",
    family: "Goals",
    question: "No goal until halftime?",
    yesProbability: 45,
    noProbability: 55,
    poolSol: "4.1 SOL",
    volumeSol: "9.3 SOL",
    timeLeft: "N/A",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Inverse goal market. Demo only for this pass.",
  },

  // ── Corner Markets ────────────────────────────────────────────────────
  {
    id: "fra-ger-corner-5m",
    fixtureId: "WC26-DEMO-FRA-GER",
    matchName: "France vs Germany",
    homeTeam: "France",
    awayTeam: "Germany",
    status: "TODAY",
    clock: "28:10",
    score: "FRA 0 - 0 GER",
    family: "Corners",
    question: "Corner in Next 5m?",
    yesProbability: 46,
    noProbability: 54,
    poolSol: "3.1 SOL",
    volumeSol: "8.5 SOL",
    timeLeft: "04:02",
    window: "28:00 -> 33:00",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Demo event market. Only mark real after TxLINE corner events/stats are wired.",
  },
  {
    id: "fra-ger-corner-total",
    fixtureId: "WC26-DEMO-FRA-GER",
    matchName: "France vs Germany",
    homeTeam: "France",
    awayTeam: "Germany",
    status: "TODAY",
    clock: "28:10",
    score: "FRA 0 - 0 GER",
    family: "Corners",
    question: "Over 8.5 corners?",
    yesProbability: 52,
    noProbability: 48,
    poolSol: "5.4 SOL",
    volumeSol: "11.2 SOL",
    timeLeft: "61:50",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Corner total market. Demo until corner stat data is available.",
  },

  // ── Penalty Markets ───────────────────────────────────────────────────
  {
    id: "esp-eng-penalty",
    fixtureId: "WC26-DEMO-ESP-ENG",
    matchName: "Spain vs England",
    homeTeam: "Spain",
    awayTeam: "England",
    status: "UPCOMING",
    clock: "0:00",
    score: "ESP 0 - 0 ENG",
    family: "Penalties",
    question: "Penalty awarded?",
    yesProbability: 23,
    noProbability: 77,
    poolSol: "2.7 SOL",
    volumeSol: "5.9 SOL",
    timeLeft: "Starts 18:00",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Penalty awarded is distinct from penalty scored. This is demo-only until real event support is configured.",
  },
  {
    id: "esp-eng-penalty-scored",
    fixtureId: "WC26-DEMO-ESP-ENG",
    matchName: "Spain vs England",
    homeTeam: "Spain",
    awayTeam: "England",
    status: "UPCOMING",
    clock: "0:00",
    score: "ESP 0 - 0 ENG",
    family: "Penalties",
    question: "Penalty scored?",
    yesProbability: 18,
    noProbability: 82,
    poolSol: "1.8 SOL",
    volumeSol: "3.4 SOL",
    timeLeft: "Starts 18:00",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Penalty conversion market. Requires penalty event + goal confirmation.",
  },

  // ── Offside Markets ───────────────────────────────────────────────────
  {
    id: "usa-mex-offside",
    fixtureId: "WC26-DEMO-USA-MEX",
    matchName: "USA vs Mexico",
    homeTeam: "USA",
    awayTeam: "Mexico",
    status: "TODAY",
    clock: "51:42",
    score: "USA 2 - 1 MEX",
    family: "Offsides",
    question: "Offside in Next 10m?",
    yesProbability: 39,
    noProbability: 61,
    poolSol: "1.9 SOL",
    volumeSol: "4.4 SOL",
    timeLeft: "08:18",
    window: "51:00 -> 61:00",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Demo event market. Offside stats must be verified before real settlement labeling.",
  },
  {
    id: "usa-mex-offside-total",
    fixtureId: "WC26-DEMO-USA-MEX",
    matchName: "USA vs Mexico",
    homeTeam: "USA",
    awayTeam: "Mexico",
    status: "TODAY",
    clock: "51:42",
    score: "USA 2 - 1 MEX",
    family: "Offsides",
    question: "Over 3.5 offsides?",
    yesProbability: 61,
    noProbability: 39,
    poolSol: "2.3 SOL",
    volumeSol: "5.1 SOL",
    timeLeft: "38:18",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Offside total market. Demo only.",
  },

  // ── Goal Total Markets ────────────────────────────────────────────────
  {
    id: "ned-por-total",
    fixtureId: "WC26-DEMO-NED-POR",
    matchName: "Netherlands vs Portugal",
    homeTeam: "Netherlands",
    awayTeam: "Portugal",
    status: "UPCOMING",
    clock: "0:00",
    score: "NED 0 - 0 POR",
    family: "Totals",
    question: "Over 2.5 goals?",
    yesProbability: 52,
    noProbability: 48,
    poolSol: "7.6 SOL",
    volumeSol: "14.9 SOL",
    timeLeft: "Starts tomorrow",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Future market family shown as product UI only for this pass.",
  },
  {
    id: "ned-por-btts",
    fixtureId: "WC26-DEMO-NED-POR",
    matchName: "Netherlands vs Portugal",
    homeTeam: "Netherlands",
    awayTeam: "Portugal",
    status: "UPCOMING",
    clock: "0:00",
    score: "NED 0 - 0 POR",
    family: "Totals",
    question: "Both teams to score?",
    yesProbability: 59,
    noProbability: 41,
    poolSol: "6.1 SOL",
    volumeSol: "12.3 SOL",
    timeLeft: "Starts tomorrow",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Both Teams To Score market. Uses final score to check both > 0.",
  },
  {
    id: "fra-ger-over-1-5",
    fixtureId: "WC26-DEMO-FRA-GER",
    matchName: "France vs Germany",
    homeTeam: "France",
    awayTeam: "Germany",
    status: "TODAY",
    clock: "28:10",
    score: "FRA 0 - 0 GER",
    family: "Totals",
    question: "Over 1.5 goals?",
    yesProbability: 68,
    noProbability: 32,
    poolSol: "8.3 SOL",
    volumeSol: "17.5 SOL",
    timeLeft: "61:50",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Goal total market using final score.",
  },

  // ── Goal Gap / Handicap Markets ───────────────────────────────────────
  {
    id: "jpn-ita-gap",
    fixtureId: "WC26-DEMO-JPN-ITA",
    matchName: "Japan vs Italy",
    homeTeam: "Japan",
    awayTeam: "Italy",
    status: "TODAY",
    clock: "74:05",
    score: "JPN 1 - 2 ITA",
    family: "Goal Gap",
    question: "Winning margin over 1.5 goals?",
    yesProbability: 31,
    noProbability: 69,
    poolSol: "4.5 SOL",
    volumeSol: "9.2 SOL",
    timeLeft: "15:55",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Score-difference family presented as roadmap/demo metadata.",
  },
  {
    id: "usa-mex-gap-1",
    fixtureId: "WC26-DEMO-USA-MEX",
    matchName: "USA vs Mexico",
    homeTeam: "USA",
    awayTeam: "Mexico",
    status: "TODAY",
    clock: "51:42",
    score: "USA 2 - 1 MEX",
    family: "Goal Gap",
    question: "USA win by 2+ goals?",
    yesProbability: 22,
    noProbability: 78,
    poolSol: "3.1 SOL",
    volumeSol: "6.7 SOL",
    timeLeft: "38:18",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Team-specific goal gap market.",
  },

  // ── Match Result Markets ──────────────────────────────────────────────
  {
    id: "esp-eng-result-draw",
    fixtureId: "WC26-DEMO-ESP-ENG",
    matchName: "Spain vs England",
    homeTeam: "Spain",
    awayTeam: "England",
    status: "UPCOMING",
    clock: "0:00",
    score: "ESP 0 - 0 ENG",
    family: "Match Result",
    question: "Draw?",
    yesProbability: 26,
    noProbability: 74,
    poolSol: "5.8 SOL",
    volumeSol: "13.2 SOL",
    timeLeft: "Starts 18:00",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Match result market using final score.",
  },
  {
    id: "esp-eng-result-spain",
    fixtureId: "WC26-DEMO-ESP-ENG",
    matchName: "Spain vs England",
    homeTeam: "Spain",
    awayTeam: "England",
    status: "UPCOMING",
    clock: "0:00",
    score: "ESP 0 - 0 ENG",
    family: "Match Result",
    question: "Spain win?",
    yesProbability: 41,
    noProbability: 59,
    poolSol: "7.2 SOL",
    volumeSol: "16.8 SOL",
    timeLeft: "Starts 18:00",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Match result market using final score.",
  },

  // ── Card Markets ──────────────────────────────────────────────────────
  {
    id: "fra-ger-card-10m",
    fixtureId: "WC26-DEMO-FRA-GER",
    matchName: "France vs Germany",
    homeTeam: "France",
    awayTeam: "Germany",
    status: "TODAY",
    clock: "28:10",
    score: "FRA 0 - 0 GER",
    family: "Cards",
    question: "Yellow card in next 10m?",
    yesProbability: 43,
    noProbability: 57,
    poolSol: "2.4 SOL",
    volumeSol: "5.6 SOL",
    timeLeft: "09:50",
    window: "28:00 -> 38:00",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Card event market. Demo only until card events are wired.",
  },
  {
    id: "usa-mex-red-card",
    fixtureId: "WC26-DEMO-USA-MEX",
    matchName: "USA vs Mexico",
    homeTeam: "USA",
    awayTeam: "Mexico",
    status: "TODAY",
    clock: "51:42",
    score: "USA 2 - 1 MEX",
    family: "Cards",
    question: "Red card in match?",
    yesProbability: 14,
    noProbability: 86,
    poolSol: "1.5 SOL",
    volumeSol: "3.2 SOL",
    timeLeft: "38:18",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/world-cup",
    description: "Red card market. Demo only.",
  },

  // ── Resolved Markets ──────────────────────────────────────────────────
  {
    id: "mar-bel-result",
    fixtureId: "WC26-DEMO-MAR-BEL",
    matchName: "Morocco vs Belgium",
    homeTeam: "Morocco",
    awayTeam: "Belgium",
    status: "RESOLVED",
    clock: "FT",
    score: "MAR 1 - 1 BEL",
    family: "Resolved",
    question: "Draw?",
    yesProbability: 100,
    noProbability: 0,
    poolSol: "5.2 SOL",
    volumeSol: "12.4 SOL",
    timeLeft: "Resolved",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/verify/mar-bel-result",
    description: "Resolved proof example for the verification UI.",
  },
  {
    id: "sen-cro-resolved",
    fixtureId: "WC26-DEMO-SEN-CRO",
    matchName: "Senegal vs Croatia",
    homeTeam: "Senegal",
    awayTeam: "Croatia",
    status: "RESOLVED",
    clock: "FT",
    score: "SEN 0 - 2 CRO",
    family: "Resolved",
    question: "Over 1.5 goals?",
    yesProbability: 100,
    noProbability: 0,
    poolSol: "4.8 SOL",
    volumeSol: "10.1 SOL",
    timeLeft: "Resolved",
    dataSource: "Simulated TxLINE-compatible event data",
    proofStatus: "demo",
    demoOnly: true,
    tradeHref: "/verify/sen-cro-resolved",
    description: "Resolved goal total example.",
  },
];

export const KICKTICK_FIXTURES = [
  {
    fixtureId: "WC26-DEMO-ARG-BRA",
    homeTeam: "Argentina",
    awayTeam: "Brazil",
    startTime: "Live now",
    status: "LIVE",
    coverage: "Score data demo, devnet live-goal flow",
  },
  {
    fixtureId: "WC26-DEMO-FRA-GER",
    homeTeam: "France",
    awayTeam: "Germany",
    startTime: "Today 16:00",
    status: "TODAY",
    coverage: "Demo corners/cards/events",
  },
  {
    fixtureId: "WC26-DEMO-ESP-ENG",
    homeTeam: "Spain",
    awayTeam: "England",
    startTime: "Today 18:00",
    status: "UPCOMING",
    coverage: "Demo match result, penalties, totals",
  },
  {
    fixtureId: "WC26-DEMO-NED-POR",
    homeTeam: "Netherlands",
    awayTeam: "Portugal",
    startTime: "Tomorrow 20:00",
    status: "UPCOMING",
    coverage: "Demo totals and goal gap",
  },
  {
    fixtureId: "WC26-DEMO-USA-MEX",
    homeTeam: "USA",
    awayTeam: "Mexico",
    startTime: "Today 14:00",
    status: "TODAY",
    coverage: "Demo offsides, cards, goal gap",
  },
  {
    fixtureId: "WC26-DEMO-JPN-ITA",
    homeTeam: "Japan",
    awayTeam: "Italy",
    startTime: "Today 20:00",
    status: "TODAY",
    coverage: "Demo goal gap",
  },
  {
    fixtureId: "WC26-DEMO-MAR-BEL",
    homeTeam: "Morocco",
    awayTeam: "Belgium",
    startTime: "Yesterday 18:00",
    status: "FINISHED",
    coverage: "Demo resolved market proof",
  },
  {
    fixtureId: "WC26-DEMO-SEN-CRO",
    homeTeam: "Senegal",
    awayTeam: "Croatia",
    startTime: "Yesterday 20:00",
    status: "FINISHED",
    coverage: "Demo resolved goal total",
  },
];

export function filterKickTickMarkets(filter: string): KickTickMarket[] {
  if (filter === "All") return KICKTICK_MARKETS;
  if (filter === "Live") return KICKTICK_MARKETS.filter(market => market.status === "LIVE");
  if (filter === "Today") return KICKTICK_MARKETS.filter(market => market.status === "TODAY" || market.status === "LIVE");
  if (filter === "Upcoming") return KICKTICK_MARKETS.filter(market => market.status === "UPCOMING");
  if (filter === "Resolved") return KICKTICK_MARKETS.filter(market => market.status === "RESOLVED" || market.family === "Resolved");
  if (filter === "5m" || filter === "15m" || filter === "45m") return KICKTICK_MARKETS.filter(market => market.question.includes(filter));
  return KICKTICK_MARKETS.filter(market => market.family === filter);
}

export function getKickTickMarket(id: string): KickTickMarket | undefined {
  return KICKTICK_MARKETS.find(market => market.id === id);
}

